### ISSUE TITLE
Improve category display on Products page

### ISSUE THREAD

**Issue by michalstruck** [InvTrack/invtrack#212]
Right now, the category display on the Products page is underwhelming to say the least. It's not really readable, and brings very little value. 
How I see it and how we discussed it with clients is very similar to how it is in the app.
Have a list of collapsible categories (in the correct order), with products as they are now inside them (in the correct order). The table header would need to change to reflect that, and I'm very open to ditching the table layout in favour of something else.

Some inspo:
https://flowbite-svelte.com/admin-dashboard
https://github.com/themesberg/flowbite-svelte-admin-dashboard

**Comment by michalstruck** [comment]
@Honsiu

**Comment by Honsiu** [comment]
:saluting_face:
